INSERT INTO member_karmunities (member_id, karmunity_id)
VALUES
    (1, (SELECT id FROM karmunity WHERE karmunity_name = 'karmunity Developers')),
    (1, (SELECT id FROM karmunity WHERE karmunity_name = 'Adie c22 iOS Capstones')),
    (1, (SELECT id FROM karmunity WHERE karmunity_name = 'Adie Project Teammates')),
    (2, (SELECT id FROM karmunity WHERE karmunity_name = 'karmunity Developers')),
    (2, (SELECT id FROM karmunity WHERE karmunity_name = 'Adie c22 iOS Capstones')),
    (2, (SELECT id FROM karmunity WHERE karmunity_name = 'Adie Project Teammates')),
    (3, (SELECT id FROM karmunity WHERE karmunity_name = 'Adie c22 iOS Capstones')),
    (4, (SELECT id FROM karmunity WHERE karmunity_name = 'Adie c22 iOS Capstones')),
    (5, (SELECT id FROM karmunity WHERE karmunity_name = 'Adie c22 iOS Capstones')),
    (6, (SELECT id FROM karmunity WHERE karmunity_name = 'Adie c22 iOS Capstones')),
    (7, (SELECT id FROM karmunity WHERE karmunity_name = 'Adie c22 iOS Capstones')),
    (7, (SELECT id FROM karmunity WHERE karmunity_name = 'Adie Project Teammates')),
    (8, (SELECT id FROM karmunity WHERE karmunity_name = 'Adie c22 iOS Capstones')),
    (8, (SELECT id FROM karmunity WHERE karmunity_name = 'Adie Project Teammates')),
    (9, (SELECT id FROM karmunity WHERE karmunity_name = 'Adie c22 iOS Capstones')),
    (10, (SELECT id FROM karmunity WHERE karmunity_name = 'Adie c22 iOS Capstones')),
    (11, (SELECT id FROM karmunity WHERE karmunity_name = 'Adie Project Teammates')),
    (12, (SELECT id FROM karmunity WHERE karmunity_name = 'Adie Project Teammates')),
    (13, (SELECT id FROM karmunity WHERE karmunity_name = 'Adie Project Teammates')),
    (14, (SELECT id FROM karmunity WHERE karmunity_name = 'Adie Project Teammates')),
    (15, (SELECT id FROM karmunity WHERE karmunity_name = 'Adie Project Teammates')),
    (16, (SELECT id FROM karmunity WHERE karmunity_name = 'ADA Instructors')),
    (17, (SELECT id FROM karmunity WHERE karmunity_name = 'ADA Instructors')),
    (18, (SELECT id FROM karmunity WHERE karmunity_name = 'ADA Instructors')),
    (19, (SELECT id FROM karmunity WHERE karmunity_name = 'ADA Instructors')),
    (20, (SELECT id FROM karmunity WHERE karmunity_name = 'ADA Instructors'));
