CREATE TABLE karma (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    giver_id BIGINT NOT NULL,
    receiver_id BIGINT NOT NULL,
    karma_points INT NOT NULL,
    karma_act VARCHAR(255) NOT NULL,
    sent_at TIMESTAMP NOT NULL,
    FOREIGN KEY (giver_id) REFERENCES member(id) ON DELETE CASCADE,
    FOREIGN KEY (receiver_id) REFERENCES member(id) ON DELETE CASCADE
);