CREATE TYPE karma_act AS ENUM (
    'ACCOUNTABILITY',
    'TEAMWORK',
    'SERVICE',
    'ENCOURAGEMENT',
    'INSPIRATION',
    'REFLECTION',
    'INITIATIVE',
    'PATIENCE',
    'RELIABILITY',
    'AUTHENTICITY',
    'KNOWLEDGE',
    'THOUGHTFULNESS'
    'GENEROSITY',
    'PRODUCTIVITY',
    'QUALITY_TIME',
    'OTHER'
    );